# Generated by Django 3.0.2 on 2020-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200710_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='blog/images/'),
            preserve_default=False,
        ),
    ]
